In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
url = 'https://www.mbust.edu.np/about/executive-team'

In [3]:
page = requests.get(url)
page.status_code

200

In [4]:
soup = BeautifulSoup(page.text, 'html.parser')

In [5]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="https://fonts.googleapis.com" rel="preconnect"/>
  <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Raleway&amp;display=swap" rel="stylesheet"/>
   <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/css/flag-icon.min.css" rel="stylesheet"/>
   <link href="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf_viewer.min.css" rel="stylesheet"/>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js">
   </script>
   <link as="style" href="https://www.mbust.edu.np/build/assets/app-eOLo5rj8.css" rel="preload">
    <link as="style" href="https://www.mbust.edu.np/build/assets/app-CNY1i59y.css" rel="preload">
     <link as="style" href="https://www.mbust.edu.np/build/assets/style-Cirb4Wv6.css" rel="preload">
      <link as="script" href="https://www.mbust.edu.np/build/assets/app-BgdqX45_.js" rel="modulepreload">
       <link data-navigate-track="reload" href="https://www.mbust.edu.np/build/assets/app-eOLo5rj8.css" rel="stylesheet"/>
       <link data-navigate-track="reload" href="https://www.mbust.edu.np/build/assets/app-CNY1i59y.css" rel="stylesheet"/>
       <link data-navigate-track="reload" href="https://www.mbust.edu.np/build/assets/style-Cirb4Wv6.css" rel="stylesheet"/>
       <script data-navigate-track="reload" src="https://www.mbust.edu.np/build/assets/app-BgdqX45_.js" type="module">
       </script>
       <!-- <link href="https://www.mbust.edu.np/css/frontend/style.css" rel="stylesheet"> -->
       <title>
        MBUST
       </title>
      </link>
     </link>
    </link>
   </link>
  </link>
 </head>
 <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script> -->
 <body class="m-0 p-0" cz-shortcut-listen="true" data-is-home="false" style=" margin:0px; padding:0px; min-height: 45vw; background-image: url('https://www.mbust.edu.np/images/medias/new-banner.png'); ">
  <header>
   <!-- Topbar -->
   <div class="bg-orange text-light py-1 small m-0">
    <div class="px-1 px-lg-5">
     <div class="d-flex flex-wrap align-items-center justify-content-between gap-2">
      <!-- Left: Important info -->
      <div class="d-flex flex-wrap align-items-center gap-3">
      </div>
      <!-- Right: Optional items -->
      <div class="d-flex align-items-center gap-3">
       <a class="text-light text-decoration-none" href="https://www.mbust.edu.np/student-portal" style="font-family:'trebuchetms', sans-serif;">
        Students' Corner
       </a>
       <a class="text-light text-decoration-none" href="https://www.mbust.edu.np/newsletter" style="font-family:'trebuchetms', sans-serif;">
        Newsletter
       </a>
       <a class="text-light text-decoration-none" href="/notices" style="font-family:'trebuchetms', sans-serif;">
        Notices
       </a>
       <a class="text-light text-decoration-none" href="/news" style="font-family:'trebuchetms', sans-serif;">
        News
       </a>
       <a class="text-light text-decoration-none" href="/events" style="font-family:'trebuchetms', sans-serif;">
        Events
       </a>
       <a class="text-light text-decoration-none" href="/contact" style="font-family:'trebuchetms', sans-serif;">
        Contact
       </a>
      </div>
     </div>
    </div>
   </div>
   <nav class="navbar navbar-expand-lg bg-light border-bottom py-2" style="position: relative;">
    <div class="container-fluid px-md-4">
     <div class="navbar-left-side d-none d-lg-block">
      <button class="btn btn-link text-dark" data-bs-target="#searchModal" data-bs-toggle="modal">
       <i class="fas fa-search fs-5">
       </i>
      </button>
     </div>
     <!-- Mobile Contribute Button (Left) -->
     <div class="d-lg-none z-1">
      <a class="btn btn-custom btn-sm px-2" href="https://www.mbust.edu.np/endowment-fund">
       Contribute
      </a>
     </div>
     <!-- Center: Logo -->
     <a class="navbar-brand position-absolute top-50 start-50 translate-middle p-0 m-0 z-1" href="https://www.mbust.edu.np">
      <img alt="Logo" class="d-none d-lg-block" src="https://www.mbust.edu.np/storage/site-logos/01KDG77B0R5J41DFXTTQG95CPV.svg" width="218"/>
      <img alt="Logo" class="d-lg-none" src="https://www.mbust.edu.np/storage/site-logos/01KDG77B0R5J41DFXTTQG95CPV.svg" width="150"/>
     </a>
     <!-- Right Side -->
     <div class="d-flex align-items-center ms-auto z-1">
      <a aria-label="Home" class="btn btn-link text-orange ms-2 d-none d-lg-block" href="https://www.mbust.edu.np">
       <i class="fas fa-home fs-5">
       </i>
      </a>
      <!-- Contribute Button -->
      <a class="mbu-heading-5 fs-5 btn btn-custom me-2 d-none d-lg-block" href="https://www.mbust.edu.np/endowment-fund">
       Contribute
      </a>
      <!--<div class="dropdown me-2">-->
      <!--  <button class="btn btn-link text-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">-->
      <!-- -->
      <!--    <span class="flag-icon flag-icon-us rounded-flag"></span>-->
      <!-- -->
      <!--  </button>-->
      <!--  <ul class="dropdown-menu dropdown-menu-end">-->
      <!--    <li>-->
      <!--      <a class="dropdown-item" href="https://www.mbust.edu.np/set-locale/en">-->
      <!--        <span class="flag-icon flag-icon-us"></span> English-->
      <!--      </a>-->
      <!--    </li>-->
      <!--    <li>-->
      <!--      <a class="dropdown-item" href="https://www.mbust.edu.np/set-locale/np">-->
      <!--        <span class="flag-icon flag-icon-np"></span> नेपाली-->
      <!--      </a>-->
      <!--    </li>-->
      <!--  </ul>-->
      <!--</div>-->
      <!-- Mobile Toggle -->
      <!-- <button class="navbar-toggler ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button> -->
      <!-- Menu Button -->
      <button aria-controls="megaMenu" aria-label="Open menu" class="btn btn-link text-dark menu-btn" data-bs-target="#megaMenu" data-bs-toggle="offcanvas" id="stickyMenuBtn" type="button">
       <svg aria-hidden="true" class="menu-svg" height="44" role="img" viewbox="0 0 44 44" width="44" xmlns="http://www.w3.org/2000/svg">
        <!-- Text -->
        <text fill="currentColor" font-family="system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif" font-size="10" font-weight="700" letter-spacing="1" text-anchor="middle" x="22" y="14">
         MENU
        </text>
        <!-- Hamburger lines -->
        <line stroke="currentColor" stroke-linecap="round" stroke-width="2.2" x1="12" x2="32" y1="22" y2="22">
        </line>
        <line stroke="currentColor" stroke-linecap="round" stroke-width="2.2" x1="12" x2="32" y1="28" y2="28">
        </line>
        <line stroke="currentColor" stroke-linecap="round" stroke-width="2.2" x1="12" x2="32" y1="34" y2="34">
        </line>
       </svg>
       <!-- <span class="menu-lines pb-2">
           <span></span><span></span><span></span>
         </span> -->
      </button>
     </div>
    </div>
    <!-- Collapsible Menu (mobile) -->
    <!-- <div class="collapse navbar-collapse" id="navbarMenu">
    <ul class="navbar-nav ms-auto text-center">
      <li class="nav-item"><a class="nav-link active" href="#">Active</a></li>
      <li class="nav-item"><a class="nav-link" href="#">Item</a></li>
      <li class="nav-item"><a class="nav-link" href="#">Another</a></li>
    </ul>
  </div> -->
   </nav>
   <!-- Search Modal -->
   <div aria-hidden="true" aria-labelledby="searchModalLabel" class="modal fade" id="searchModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
     <div class="modal-content">
      <div class="modal-header">
       <h5 class="modal-title" id="searchModalLabel">
        Search
       </h5>
       <button aria-label="Close" class="btn-close" data-bs-dismiss="modal" type="button">
       </button>
      </div>
      <div class="modal-body">
       <form action="https://www.mbust.edu.np/search" method="GET">
        <input class="form-control" name="q" placeholder="Search..." type="text"/>
       </form>
      </div>
     </div>
    </div>
   </div>
   <!-- Fullscreen Mega Menu  -->
   <div aria-labelledby="megaMenuLabel" class="offcanvas offcanvas-top menu-offcanvas" id="megaMenu" tabindex="-1">
    <!-- Top Bar -->
    <div class="offcanvas-header">
     <div class="header-left d-none d-md-block">
      <img alt="MBUST Logo" class="menu-logo" src="https://www.mbust.edu.np/storage/site-logos/01KDG77B0R5J41DFXTTQG95CPV.svg"/>
     </div>
     <a class="p-1" href="https://www.mbust.edu.np/notices" style="font-family:'trebuchetms', sans-serif;">
      Notices
     </a>
     <a class="p-1" href="https://www.mbust.edu.np/news" style="font-family:'trebuchetms', sans-serif;">
      News
     </a>
     <a class="p-1" href="https://www.mbust.edu.np/events" style="font-family:'trebuchetms', sans-serif;">
      Events
     </a>
     <a class="p-1" href="https://www.mbust.edu.np/contact" style="font-family:'trebuchetms', sans-serif;">
      Contacts
     </a>
     <button aria-label="Close" class="btn-close-custom" data-bs-dismiss="offcanvas" style="font-family:'trebuchetms', sans-serif;" type="button">
      Close
      <span class="close-icon">
       ✕
      </span>
     </button>
    </div>
    <!-- Body -->
    <div class="offcanvas-body">
     <!-- Mobile Search Bar (Below Logo) -->
     <div class="container-fluid px-4 mt-2 d-lg-none">
      <form action="https://www.mbust.edu.np/search" class="w-100" method="GET">
       <div class="input-group">
        <span class="input-group-text bg-white border-dark border-1 border-end-0 rounded-start">
         <i class="fas fa-search text-muted">
         </i>
        </span>
        <input class="form-control border-start-0 ps-0 rounded-end" name="q" placeholder="Search..." type="text"/>
       </div>
      </form>
     </div>
     <div class="menu-container">
      <div class="menu-layout">
       <!-- Left Main Menu -->
       <div class="menu-left">
        <nav class="nav flex-column" id="megaMenuTabs" role="tablist">
         <button class="menu-main-link" data-bs-target="#tab-mbu-glance" data-bs-toggle="tab" role="tab" type="button">
          <div class="mbu-heading-2 fs-3 p-2 mb-0">
           MBUST at a Glance
          </div>
         </button>
         <button class="menu-main-link active" data-bs-target="#tab-about" data-bs-toggle="tab" role="tab" type="button">
          <div class="mbu-heading-2 fs-3 p-2 mb-0">
           About
          </div>
         </button>
         <button class="menu-main-link" data-bs-target="#tab-academics" data-bs-toggle="tab" role="tab" type="button">
          <div class="mbu-heading-2 fs-3 p-2 mb-0">
           Academics
          </div>
         </button>
         <button class="menu-main-link" data-bs-target="#tab-admissions" data-bs-toggle="tab" role="tab" type="button">
          <div class="mbu-heading-2 fs-3 p-2 mb-0">
           Admissions
          </div>
         </button>
         <button class="menu-main-link" data-bs-target="#tab-student-corner" data-bs-toggle="tab" role="tab" type="button">
          <div class="mbu-heading-2 fs-3 p-2 mb-0">
           Students' Corner
          </div>
         </button>
         <button class="menu-main-link" data-bs-target="#tab-research" data-bs-toggle="tab" role="tab" type="button">
          <div class="mbu-heading-2 fs-3 p-2 mb-0">
           Research
          </div>
         </button>
         <button class="menu-main-link" data-bs-target="#tab-endowment" data-bs-toggle="tab" role="tab" type="button">
          <div class="mbu-heading-2 fs-3 p-2 mb-0">
           Donation
          </div>
         </button>
         <!--<button class="menu-main-link" data-bs-toggle="tab" data-bs-target="#tab-partnership" type="button" role="tab">-->
         <!--  <p class="mbu-heading-5 p-2">Partnership</p>-->
         <!--</button>-->
         <!-- <button class="menu-main-link " data-bs-toggle="tab" data-bs-target="#tab-contact" type="button" role="tab">
                <p class="mbu-heading-2 fs-3 fw-bold p-2 mb-0">Contact</p>
              </button> -->
        </nav>
       </div>
       <!-- Right Sub Menu -->
       <div class="menu-right ps-4">
        <div class="tab-content">
         <!-- About -->
         <div class="tab-pane fade show active" id="tab-about" role="tabpanel">
          <div class="mbu-heading-2 section-title" style="font-weight:400; font-size: 34px;">
           About
          </div>
          <!-- <p class="section-description">Learn more about MBUST.</p> -->
          <div class="menu-links">
           <a class="menu-sub-link" href="https://www.mbust.edu.np/about">
            Who are We
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/about/mission-vision">
            Mission and Vision
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/about/board-of-trustees">
            Board of Trustees
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/about/honorary-members">
            Honorary Positions
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/about/president-message">
            Message from the President
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/about/organization-structure">
            Organizational Structure
           </a>
           <a class="menu-sub-link active" href="https://www.mbust.edu.np/about/executive-team">
            Executive Team
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/about/faculty-staff-students">
            Academic Team
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/about/administrative">
            Administrative Team
           </a>
           <!--<a class="menu-sub-link" href="https://www.mbust.edu.np/about/future-plans">Future Plans</a>-->
           <a class="menu-sub-link" href="https://www.mbust.edu.np/partnership">
            Partnerships
           </a>
          </div>
         </div>
         <!-- Academics -->
         <div class="tab-pane fade" id="tab-academics" role="tabpanel">
          <div class="mbu-heading-2 section-title" style="font-weight:400; font-size: 34px;">
           Academics
          </div>
          <!-- <p class="section-description">Excellence in education and research.</p> -->
          <!-- <div class="mbu-heading-6 subsection-title">Academic Programs</div> -->
          <div class="menu-links">
           <a class="menu-sub-link" href="https://www.mbust.edu.np/academics">
            Overview
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/academics/undergraduate-studies">
            Undergraduate Studies
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/academics/graduate-studies">
            Graduate Studies - Master
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/academics/phd-studies">
            Graduate Studies - Doctorate
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/academics/courses">
            Course List
           </a>
          </div>
         </div>
         <!-- Admissions -->
         <div class="tab-pane fade" id="tab-admissions" role="tabpanel">
          <div class="mbu-heading-2 section-title" style="font-weight:400; font-size: 34px;">
           Admissions
          </div>
          <!-- <p class="section-description">Join our vibrant community.</p> -->
          <div class="menu-links">
           <a class="menu-sub-link" href="https://www.mbust.edu.np/admission">
            Overview
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/admission/tuition-breakdown">
            Tuition and Other Fees
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/admission/aid-and-scholarship">
            Support and Scholarships
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/admission/accomodation">
            Accommodation
           </a>
          </div>
         </div>
         <div class="tab-pane fade" id="tab-student-corner" role="tabpanel">
          <div class="mbu-heading-2 section-title" style="font-weight:400; font-size: 34px;">
           Student Corner
          </div>
          <div class="menu-links">
           <a class="menu-sub-link" href="https://www.mbust.edu.np/student-corner">
            Overview
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/student-corner#sp-section-1">
            Students' at MBUST
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/student-corner#sp-section-2">
            Academic Calendar
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/student-corner#sp-section-3">
            Imporant Dates
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/student-corner#sp-section-4">
            Alumni
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/student-corner#sp-section-5">
            Social Support
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/student-corner#sp-section-6">
            Students' Clubs
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/student-corner#sp-section-7">
            Professors
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/student-corner#sp-section-8">
            Admission Calendar
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/student-corner#sp-verify-api">
            Student Result
           </a>
          </div>
         </div>
         <!-- MBU at a Glance -->
         <div class="tab-pane fade" id="tab-mbu-glance" role="tabpanel">
          <div class="mbu-heading-2 section-title" style="font-weight:400; font-size: 34px;">
           MBUST at a Glance
          </div>
          <!-- <p class="section-description">Discover our campus and culture.</p> -->
          <div class="menu-links">
           <a class="menu-sub-link" href="https://www.mbust.edu.np/mbu-at-glance">
            Overview
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/mbu-at-glance/explore-chitlang">
            Explore Chitlang
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/mbu-at-glance/the-university-campus">
            University Campus
           </a>
          </div>
         </div>
         <!-- Research -->
         <div class="tab-pane fade" id="tab-research" role="tabpanel">
          <div class="mbu-heading-2 section-title" style="font-weight:400; font-size: 34px;">
           Research
          </div>
          <!-- <p class="section-description">Innovation and discovery.</p> -->
          <div class="menu-links">
           <a class="menu-sub-link" href="https://www.mbust.edu.np/research">
            Overview
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/research/ongoing-research">
            Ongoing Research
           </a>
           <a class="menu-sub-link" href="https://www.mbust.edu.np/research/research-publications">
            Publications
           </a>
           <div class="mt-3 mb-2 fw-bold text-muted small text-uppercase">
            Facilities
           </div>

In [6]:
container = soup.select_one("div.container.ag-container")
print(container)

<div class="container ag-container">
<div class="text-center mb-5">
<h2 class="mbu-heading-2">Executive Leadership</h2>
<p class="mbust-bot-subtitle">The core leadership team driving MBUST's vision and mission</p>
</div>
<div class="row justify-content-center mb-4">
<div class="col-12">
<div class="mbust-member-card featured clearfix">
<div class="member-image-box">
<img alt="" class="rounded-circle border" src="https://www.mbust.edu.np/storage/posts/01KHJMD0SP4TW3J3A1BXP7JXC4.jpg"/>
</div>
<h5 class="mbu-heading-4 fs-4">Dr. Rajendra Dhoj Joshi</h5>
<span class="member-role">President</span>
<div class="member-bio">
                                Chief executive officer responsible for overall leadership and strategic direction
                            </div>
</div>
</div>
</div>
<div class="row g-4">
<div class="col-lg-6">
<div class="mbust-member-card clearfix h-100">
<div class="member-image-box">
<img alt="" class="img-fluid rounded-circle border" src="https://www.mbust.edu.np/storage/posts/01KGM4Q3MG96H9RW64BBYVYABG.jpeg"/>
</div>
<h5 class="mbu-heading-5 fs-4">Dr. Dinesh Raj Bhuju</h5>
<span class="member-role">Vice President - Academic and Research</span>
<div class="member-bio">
                                    Oversees all academic programs and
educational initiatives
                                </div>
</div>
</div>
<div class="col-lg-6">
<div class="mbust-member-card clearfix h-100">
<div class="member-image-box">
<img alt="" class="img-fluid rounded-circle border" src="https://www.mbust.edu.np/storage/posts/01KKB8CYG0SA4BG5ZZFD38XQC7.png"/>
</div>
<h5 class="mbu-heading-5 fs-4">Mr. Padma Sunder Joshi</h5>
<span class="member-role">Vice President - Admin &amp;  Finance</span>
<div class="member-bio">
                                    Oversees administrative operations and management
                                </div>
</div>
</div>
<div class="col-lg-6">
<div class="mbust-member-card clearfix h-100">
<div class="member-image-box">
<img alt="" class="img-fluid rounded-circle border" src="https://www.mbust.edu.np/storage/posts/01KGM1MT91VYSZMJA3MQ7X8GYQ.PNG"/>
</div>
<h5 class="mbu-heading-5 fs-4">Dr. Kirti Kusum Joshi</h5>
<span class="member-role">Director, Institute of Applied Sciences</span>
<div class="member-bio">
                                    Manages academic programs under the institute

                                </div>
</div>
</div>
<div class="col-lg-6">
<div class="mbust-member-card clearfix h-100">
<div class="member-image-box">
<img alt="" class="img-fluid rounded-circle border" src="https://www.mbust.edu.np/storage/posts/01KGMB5M8Y0DM7VVTV8BQ07QPW.jpg"/>
</div>
<h5 class="mbu-heading-5 fs-4">Dr. Sanjay Nath Khanal</h5>
<span class="member-role">Academic Advisor</span>
<div class="member-bio">
                                    Advises on academic administration
                                </div>
</div>
</div>
</div>
</div>

In [7]:
member = soup.find_all("div", class_="mbust-member-card")
print(member)

[<div class="mbust-member-card featured clearfix">
<div class="member-image-box">
<img alt="" class="rounded-circle border" src="https://www.mbust.edu.np/storage/posts/01KHJMD0SP4TW3J3A1BXP7JXC4.jpg"/>
</div>
<h5 class="mbu-heading-4 fs-4">Dr. Rajendra Dhoj Joshi</h5>
<span class="member-role">President</span>
<div class="member-bio">
                                Chief executive officer responsible for overall leadership and strategic direction
                            </div>
</div>, <div class="mbust-member-card clearfix h-100">
<div class="member-image-box">
<img alt="" class="img-fluid rounded-circle border" src="https://www.mbust.edu.np/storage/posts/01KGM4Q3MG96H9RW64BBYVYABG.jpeg"/>
</div>
<h5 class="mbu-heading-5 fs-4">Dr. Dinesh Raj Bhuju</h5>
<span class="member-role">Vice President - Academic and Research</span>
<div class="member-bio">
                                    Oversees all academic programs and
educational initiatives
                                </div>
</div>, <div class="mbust-member-card clearfix h-100">
<div class="member-image-box">
<img alt="" class="img-fluid rounded-circle border" src="https://www.mbust.edu.np/storage/posts/01KKB8CYG0SA4BG5ZZFD38XQC7.png"/>
</div>
<h5 class="mbu-heading-5 fs-4">Mr. Padma Sunder Joshi</h5>
<span class="member-role">Vice President - Admin &amp;  Finance</span>
<div class="member-bio">
                                    Oversees administrative operations and management
                                </div>
</div>, <div class="mbust-member-card clearfix h-100">
<div class="member-image-box">
<img alt="" class="img-fluid rounded-circle border" src="https://www.mbust.edu.np/storage/posts/01KGM1MT91VYSZMJA3MQ7X8GYQ.PNG"/>
</div>
<h5 class="mbu-heading-5 fs-4">Dr. Kirti Kusum Joshi</h5>
<span class="member-role">Director, Institute of Applied Sciences</span>
<div class="member-bio">
                                    Manages academic programs under the institute

                                </div>
</div>, <div class="mbust-member-card clearfix h-100">
<div class="member-image-box">
<img alt="" class="img-fluid rounded-circle border" src="https://www.mbust.edu.np/storage/posts/01KGMB5M8Y0DM7VVTV8BQ07QPW.jpg"/>
</div>
<h5 class="mbu-heading-5 fs-4">Dr. Sanjay Nath Khanal</h5>
<span class="member-role">Academic Advisor</span>
<div class="member-bio">
                                    Advises on academic administration
                                </div>
</div>]

In [8]:
type(member)

bs4.element.ResultSet

In [9]:
first_member = member[0]

img = first_member.find("img")
name = first_member.find("h5").text.strip()
position = first_member.find("span", class_="member-role").text.strip()

print(name)
print(position)
print(img["src"])

Dr. Rajendra Dhoj Joshi
President
https://www.mbust.edu.np/storage/posts/01KHJMD0SP4TW3J3A1BXP7JXC4.jpg

In [10]:
import pandas as pd

members = soup.find_all("div", class_="mbust-member-card")

data = []

for member in members:
    img = member.find("img")["src"]
    name = member.find("h5").text.strip()
    position = member.find("span", class_="member-role").text.strip()

    data.append({
        "name": name,
        "position": position,
        "image": img
    })

df = pd.DataFrame(data)

df.to_csv("mbust_executive_leadership.csv", index=False)

print(df)

                      name                                 position  \
0  Dr. Rajendra Dhoj Joshi                                President
1     Dr. Dinesh Raj Bhuju   Vice President - Academic and Research
2   Mr. Padma Sunder Joshi        Vice President - Admin &  Finance
3    Dr. Kirti Kusum Joshi  Director, Institute of Applied Sciences
4   Dr. Sanjay Nath Khanal                         Academic Advisor

                                               image
0  https://www.mbust.edu.np/storage/posts/01KHJMD...
1  https://www.mbust.edu.np/storage/posts/01KGM4Q...
2  https://www.mbust.edu.np/storage/posts/01KKB8C...
3  https://www.mbust.edu.np/storage/posts/01KGM1M...
4  https://www.mbust.edu.np/storage/posts/01KGMB5...

In [11]:
import os
import requests
import pandas as pd

# Create folder if it doesn't exist
os.makedirs("stakeholders", exist_ok=True)

members = soup.find_all("div", class_="mbust-member-card")

data = []

for member in members:
    img_url = member.find("img")["src"]
    name = member.find("h5").text.strip()
    position = member.find("span", class_="member-role").text.strip()

    # Create a safe filename
    filename = (
        name.replace(".", "")
            .replace(" ", "_")
            .replace("/", "_")
            + ".jpg"
    )

    image_path = os.path.join("stakeholders", filename)

    # Download image
    response = requests.get(img_url)
    if response.status_code == 200:
        with open(image_path, "wb") as f:
            f.write(response.content)

    # Save information
    data.append({
        "name": name,
        "position": position,
        "image": image_path
    })

# Save CSV
df = pd.DataFrame(data)
df.to_csv("stakeholders.csv", index=False)

print("Done!")

Done!

In [12]:
df = pd.read_csv("stakeholders.csv")
df.head()

,name,position,image
0,Dr. Rajendra Dhoj Joshi,President,stakeholders/Dr_Rajendra_Dhoj_Joshi.jpg
1,Dr. Dinesh Raj Bhuju,Vice President - Academic and Research,stakeholders/Dr_Dinesh_Raj_Bhuju.jpg
2,Mr. Padma Sunder Joshi,Vice President - Admin & Finance,stakeholders/Mr_Padma_Sunder_Joshi.jpg
3,Dr. Kirti Kusum Joshi,"Director, Institute of Applied Sciences",stakeholders/Dr_Kirti_Kusum_Joshi.jpg
4,Dr. Sanjay Nath Khanal,Academic Advisor,stakeholders/Dr_Sanjay_Nath_Khanal.jpg

In [13]:
df['image'] = df['image'].str.split('/').str[1]

In [14]:
df

,name,position,image
0,Dr. Rajendra Dhoj Joshi,President,Dr_Rajendra_Dhoj_Joshi.jpg
1,Dr. Dinesh Raj Bhuju,Vice President - Academic and Research,Dr_Dinesh_Raj_Bhuju.jpg
2,Mr. Padma Sunder Joshi,Vice President - Admin & Finance,Mr_Padma_Sunder_Joshi.jpg
3,Dr. Kirti Kusum Joshi,"Director, Institute of Applied Sciences",Dr_Kirti_Kusum_Joshi.jpg
4,Dr. Sanjay Nath Khanal,Academic Advisor,Dr_Sanjay_Nath_Khanal.jpg

#### Download the images

In [15]:
import os
import requests
import pandas as pd

# Create folder
os.makedirs("stakeholders", exist_ok=True)

members = soup.find_all("div", class_="mbust-member-card")

data = []

for member in members:
    # Extract information
    img_url = member.find("img")["src"]
    name = member.find("h5").text.strip()
    position = member.find("span", class_="member-role").text.strip()

    # Create a safe filename
    filename = (
        name.replace(".", "")
            .replace(" ", "_")
            .replace("/", "_")
            + ".jpg"
    )

    image_path = os.path.join("stakeholders", filename)

    # Download image
    response = requests.get(img_url)

    if response.status_code == 200:
        with open(image_path, "wb") as f:
            f.write(response.content)

        print(f"Downloaded: {filename}")
    else:
        print(f"Failed: {name}")

    # Save information
    data.append({
        "name": name,
        "position": position,
        "image": image_path
    })

# Save CSV
df = pd.DataFrame(data)
df.to_csv("stakeholders.csv", index=False)

print("Done!")

Downloaded: Dr_Rajendra_Dhoj_Joshi.jpg
Downloaded: Dr_Dinesh_Raj_Bhuju.jpg
Downloaded: Mr_Padma_Sunder_Joshi.jpg
Downloaded: Dr_Kirti_Kusum_Joshi.jpg
Downloaded: Dr_Sanjay_Nath_Khanal.jpg
Done!